### ISSUE TITLE
Map + track not rendering

### ISSUE THREAD

**Issue by bcardarella** [opensailing/nautic_net_web#15]
For July 17

<img width="1258" alt="Screenshot 2023-07-17 at 10 13 19 PM" src="https://github.com/opensailing/nautic_net_web/assets/18524/b7628e25-a378-4c08-83a2-fa71f40c56d6">

**Comment by schrockwell** [comment]
Fixed through a series of performance improvement PRs (#24, #29, etc), and also scaling the instance from 512MB to 1024MB.
