### ISSUE TITLE
MapLive renders incorrect coordinates

### ISSUE THREAD

**Issue by schrockwell** [opensailing/nautic_net_web#17]
I assume it is trying to render (0,0) coords, which we should probably throw out and/or ignore

![image](https://github.com/opensailing/nautic_net_web/assets/30214/c0091550-2696-4180-9999-4368c671bc84)

**Comment by schrockwell** [comment]
Actually the value is `POINT(922.3372192382812 922.3372192382812)` which is clearly pretty wrong… we should throw out any coordinate values outside the normal bounds.

**Comment by CaptChrisD** [comment]
When processing the GNSS PG you likely want to look at field 9 (Integrity) and discard messages that are marked unsafe and maybe also caution. This is common when the receiver only has a few satellites during startup.

**Comment by schrockwell** [comment]
Fixed this on the web, but we should do additional filtering on device.
